cd sa-head/en-entries
make DICTS='apte-1890'
make DICTS='aufrecht-catalogus-catalogorum'
make DICTS='benfey'
make DICTS='capeller-sanskrit-english'
make DICTS='edgerton-buddhist-hybrid'
make DICTS='goldstucker'
make DICTS='indian-epigraphical-glossary'
make DICTS='macdonell'
make DICTS='Meulenbeld-Sanskrit-Names-of-Plants'
make DICTS='mw-1872'
make DICTS='Personal-and-Geographical-Names-in-the-Gupta-Inscriptions'
make DICTS='shabda-sAgara'
make DICTS='Vedic-Index-of-Names-and-Subjects'
make DICTS='wilson'
make DICTS='yates'
make DICTS='lanman'
make DICTS='vaidya'
cd ../../sa-head/german-entries
make DICTS='Bohtlingk-and-Roth-Grosses-Petersburger-Worterbuch'
make DICTS='Bohtlingk-Sanskrit-Worterbuch-in-kurzerer-Fassung'
make DICTS='capeller-sanskrit-german'
make DICTS='Schmidt-Nachtrage-zum-Sanskrit-Worterbuch'
make DICTS='grassman-sanskrit-german'
cd ../../sa-head/other-entries
make DICTS='bopp'
cd ../../sa-head/french-entries
make DICTS='burnouf'
make DICTS='Stchoupak-Sanscrit-French'
cd ../../sa-head/sa-entries
make DICTS='kalpadruma-sa'
make DICTS='vAchaspatyam-sa'
cd ../../en-head
make DICTS='borooah'
make DICTS='mw-english-sanskrit'
cd ../sa-kAvya
make DICTS='index-names-mahabharata'

