.PHONY: all

all:
	make -C sa-indexFileEntries all
	make -C en-indexFileEntries all
	make -C other-indic-indexFileEntries all
	make -C other-indexFileEntries all

tars:
	make -C sa-indexFileEntries tars
	make -C en-indexFileEntries tars
	make -C other-indic-indexFileEntries tars
	make -C other-indexFileEntries tars

tarlist:
	make -C sa-indexFileEntries tarlist
	make -C en-indexFileEntries tarlist
	make -C other-indic-indexFileEntries tarlist
	make -C other-indexFileEntries tarlist

